In [15]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, label_binarize, LabelEncoder
from sklearn.model_selection import KFold, cross_val_predict
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report, roc_curve, auc as sklearn_auc
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.naive_bayes import BernoulliNB, GaussianNB, MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
from tqdm import tqdm

from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, classification_report, mean_absolute_error, mean_squared_error, r2_score

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix


# Suppress warnings
warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore", category=UserWarning)
warnings.filterwarnings("ignore", category=RuntimeWarning)


random_state = 42


files_bfi2 = [
    "Human_GPT3.5_persona_BFI2.xlsx",
    "Human_GPT3.5_shape_BFI2.xlsx",
    "Human_GPT4_persona_BFI2.xlsx",
    "Human_GPT4_shape_BFI2.xlsx",
    'Human_LLaMA3_persona_BFI2.xlsx',
    "Human_LLaMA3_shape_BFI2.xlsx",
]

files_hexao= [
    "Human_GPT3.5_persona_HEXAO.xlsx",
    "Human_GPT3.5_shape_HEXAO.xlsx",
    "Human_GPT4_persona_HEXAO.xlsx",
    "Human_GPT4_shape_HEXAO.xlsx",
    "Human_LLaMA3_persona_HEXAO.xlsx",
    "Human_LLaMA3_shape_HEXAO.xlsx"
]

# Testing

In [13]:
df_test = pd.read_excel(f'data/{files_bfi2[0]}')

In [16]:
df_lm = df_test[df_test["label"] == "LM"].reset_index(drop=True)
df_human = df_test[df_test["label"] == "Human"].reset_index(drop=True)
df_human = df_human.sample(300).reset_index(drop=True)  # we only have 300 for LM

df_test = pd.concat([df_lm, df_human], axis=0)
items_count = 60
cols_to_regres = [f"item{i}" for i in range(1, items_count+1)]

X = df_test[cols_to_regres]
y = df_test["label"]

label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)
# print(y_encoded) 

# Initialize the logistic regression model (multinomial for multiple categories)
model = LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=200)

kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
for train_index, test_index in kf.split(X, y_encoded):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y_encoded[train_index], y_encoded[test_index]

model.fit(X_train, y_train)
        
# Predict on the test set
y_pred = model.predict(X_test)


print("accuracy_score", accuracy_score(y_test, y_pred))
print("precision_score", precision_score(y_test, y_pred, average='macro'))
print("recall_score", recall_score(y_test, y_pred, average='macro'))
print("f1_score", f1_score(y_test, y_pred, average='macro'))
print("mean_absolute_error", mean_absolute_error(y_test, y_pred))
print("mean_squared_error", mean_squared_error(y_test, y_pred))
print("r2_score", r2_score(y_test, y_pred))
print("mean_squared_error", np.sqrt(mean_squared_error(y_test, y_pred)))

try:
    print("roc_auc_score", roc_auc_score(y_test, model.predict_proba(X_test), multi_class='ovr', average='macro'))
except ValueError:
    print("roc_auc_score", None)

accuracy_score 0.95
precision_score 0.9520089285714286
recall_score 0.95
f1_score 0.949944382647386
mean_absolute_error 0.05
mean_squared_error 0.05
r2_score 0.8
mean_squared_error 0.22360679774997896
roc_auc_score None

In [17]:
df_test = pd.read_excel(f'data/{files_bfi2[1]}')

df_lm = df_test[df_test["label"] == "LM"].reset_index(drop=True)
df_human = df_test[df_test["label"] == "Human"].reset_index(drop=True)
df_human = df_human.sample(300).reset_index(drop=True)  # we only have 300 for LM

df_test = pd.concat([df_lm, df_human], axis=0)
items_count = 60
cols_to_regres = [f"item{i}" for i in range(1, items_count+1)]

X = df_test[cols_to_regres]
y = df_test["label"]

label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)
# print(y_encoded) 

# Initialize the logistic regression model (multinomial for multiple categories)
model = LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=200)

kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
for train_index, test_index in kf.split(X, y_encoded):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y_encoded[train_index], y_encoded[test_index]

model.fit(X_train, y_train)
        
# Predict on the test set
y_pred = model.predict(X_test)


print("accuracy_score", accuracy_score(y_test, y_pred))
print("precision_score", precision_score(y_test, y_pred, average='macro'))
print("recall_score", recall_score(y_test, y_pred, average='macro'))
print("f1_score", f1_score(y_test, y_pred, average='macro'))
print("mean_absolute_error", mean_absolute_error(y_test, y_pred))
print("mean_squared_error", mean_squared_error(y_test, y_pred))
print("r2_score", r2_score(y_test, y_pred))
print("mean_squared_error", np.sqrt(mean_squared_error(y_test, y_pred)))

try:
    print("roc_auc_score", roc_auc_score(y_test, model.predict_proba(X_test), multi_class='ovr', average='macro'))
except ValueError:
    print("roc_auc_score", None)

accuracy_score 0.975
precision_score 0.9751319811058627
recall_score 0.975
f1_score 0.9749982637683172
mean_absolute_error 0.025
mean_squared_error 0.025
r2_score 0.9
mean_squared_error 0.15811388300841897
roc_auc_score None

In [14]:
df_test

,item1,item2,item3,item4,item5,item6,item7,item8,item9,item10,...,item52,item53,item54,item55,item56,item57,item58,item59,item60,label
0,3,3,4,4,3,3,5,4,3,4,...,5,5,3,3,3,3,4,3,3,LM
1,1,5,4,1,3,2,5,4,2,5,...,3,5,3,3,5,2,4,2,3,LM
2,1,1,3,4,3,4,4,2,3,3,...,2,3,3,3,4,2,3,3,3,LM
3,2,5,4,2,3,2,5,4,2,5,...,5,4,2,3,4,4,5,3,3,LM
4,3,5,4,3,3,3,5,4,4,5,...,5,5,3,3,4,3,4,3,5,LM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,1,5,2,4,2,1,5,2,4,5,...,5,5,4,4,4,2,5,5,4,Human
296,5,5,2,1,5,2,4,4,2,4,...,5,4,1,4,4,4,2,1,5,Human
297,4,5,2,4,3,2,5,2,4,5,...,5,4,4,2,2,2,1,4,4,Human
298,4,4,5,4,2,4,4,4,4,4,...,4,4,2,2,4,2,4,4,4,Human
299,4,4,4,2,4,1,5,4,2,5,...,5,4,4,5,4,4,2,4,4,Human

In [16]:
X = df_test[cols_to_regres]
y = df_test["label"]

In [18]:
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)
# print(y_encoded) 

# Initialize the logistic regression model (multinomial for multiple categories)
model = LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=200)

In [20]:
kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
for train_index, test_index in kf.split(X, y_encoded):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y_encoded[train_index], y_encoded[test_index]

In [22]:
model.fit(X_train, y_train)
        
# Predict on the test set
y_pred = model.predict(X_test)

In [23]:
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0])

In [24]:
y_test

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
print("accuracy_score", accuracy_score(y_test, y_pred))
print("precision_score", precision_score(y_test, y_pred, average='macro'))
print("recall_score", recall_score(y_test, y_pred, average='macro'))
print("f1_score", f1_score(y_test, y_pred, average='macro'))
print("mean_absolute_error", mean_absolute_error(y_test, y_pred))
print("mean_squared_error", mean_squared_error(y_test, y_pred))
print("r2_score", r2_score(y_test, y_pred))
print("mean_squared_error", np.sqrt(mean_squared_error(y_test, y_pred)))

try:
    print("roc_auc_score", roc_auc_score(y_test, model.predict_proba(X_test), multi_class='ovr', average='macro'))
except ValueError:
    print("roc_auc_score", None)

accuracy_score 0.925
precision_score 0.9347826086956521
recall_score 0.925
f1_score 0.9245757385292268
mean_absolute_error 0.075
mean_squared_error 0.075
r2_score 0.7
mean_squared_error 0.27386127875258304
roc_auc_score None

In [27]:
X_with_const = sm.add_constant(X_train)
logit_model = sm.MNLogit(y_train, X_with_const)
result = logit_model.fit()
p_values = result.pvalues

Optimization terminated successfully.
         Current function value: nan
         Iterations 23

In [28]:
p_values

         0
const  NaN
item1  NaN
item2  NaN
item3  NaN
item4  NaN
...     ..
item56 NaN
item57 NaN
item58 NaN
item59 NaN
item60 NaN

[61 rows x 1 columns]

In [30]:
logit_model = sm.MNLogit(y_train, X_train)
result = logit_model.fit(disp=0)

In [33]:
results = []
summary_frame = result.summary2().tables[1]
results.append({
    'parameters': result.params,
    'pvalues': result.pvalues,
    'model_summary': summary_frame
})

In [34]:
results

[{'parameters':          0
  item1  NaN
  item2  NaN
  item3  NaN
  item4  NaN
  item5  NaN
  item6  NaN
  item7  NaN
  item8  NaN
  item9  NaN
  item10 NaN
  item11 NaN
  item12 NaN
  item13 NaN
  item14 NaN
  item15 NaN
  item16 NaN
  item17 NaN
  item18 NaN
  item19 NaN
  item20 NaN
  item21 NaN
  item22 NaN
  item23 NaN
  item24 NaN
  item25 NaN
  item26 NaN
  item27 NaN
  item28 NaN
  item29 NaN
  item30 NaN
  item31 NaN
  item32 NaN
  item33 NaN
  item34 NaN
  item35 NaN
  item36 NaN
  item37 NaN
  item38 NaN
  item39 NaN
  item40 NaN
  item41 NaN
  item42 NaN
  item43 NaN
  item44 NaN
  item45 NaN
  item46 NaN
  item47 NaN
  item48 NaN
  item49 NaN
  item50 NaN
  item51 NaN
  item52 NaN
  item53 NaN
  item54 NaN
  item55 NaN
  item56 NaN
  item57 NaN
  item58 NaN
  item59 NaN
  item60 NaN,
  'pvalues':          0
  item1  NaN
  item2  NaN
  item3  NaN
  item4  NaN
  item5  NaN
  item6  NaN
  item7  NaN
  item8  NaN
  item9  NaN
  item10 NaN
  item11 NaN
  item12 NaN
  item13 NaN
  item14 NaN
  item15 NaN
  item16 NaN
  item17 NaN
  item18 NaN
  item19 NaN
  item20 NaN
  item21 NaN
  item22 NaN
  item23 NaN
  item24 NaN
  item25 NaN
  item26 NaN
  item27 NaN
  item28 NaN
  item29 NaN
  item30 NaN
  item31 NaN
  item32 NaN
  item33 NaN
  item34 NaN
  item35 NaN
  item36 NaN
  item37 NaN
  item38 NaN
  item39 NaN
  item40 NaN
  item41 NaN
  item42 NaN
  item43 NaN
  item44 NaN
  item45 NaN
  item46 NaN
  item47 NaN
  item48 NaN
  item49 NaN
  item50 NaN
  item51 NaN
  item52 NaN
  item53 NaN
  item54 NaN
  item55 NaN
  item56 NaN
  item57 NaN
  item58 NaN
  item59 NaN
  item60 NaN,
  'model_summary':          y = 0  Coef.  Std.Err.   t  P>|t|  [0.025  0.975]
  item1    item1    NaN       NaN NaN    NaN     NaN     NaN
  item2    item2    NaN       NaN NaN    NaN     NaN     NaN
  item3    item3    NaN       NaN NaN    NaN     NaN     NaN
  item4    item4    NaN       NaN NaN    NaN     NaN     NaN
  item5    item5    NaN       NaN NaN    NaN     NaN     NaN
  item6    item6    NaN       NaN NaN    NaN     NaN     NaN
  item7    item7    NaN       NaN NaN    NaN     NaN     NaN
  item8    item8    NaN       NaN NaN    NaN     NaN     NaN
  item9    item9    NaN       NaN NaN    NaN     NaN     NaN
  item10  item10    NaN       NaN NaN    NaN     NaN     NaN
  item11  item11    NaN       NaN NaN    NaN     NaN     NaN
  item12  item12    NaN       NaN NaN    NaN     NaN     NaN
  item13  item13    NaN       NaN NaN    NaN     NaN     NaN
  item14  item14    NaN       NaN NaN    NaN     NaN     NaN
  item15  item15    NaN       NaN NaN    NaN     NaN     NaN
  item16  item16    NaN       NaN NaN    NaN     NaN     NaN
  item17  item17    NaN       NaN NaN    NaN     NaN     NaN
  item18  item18    NaN       NaN NaN    NaN     NaN     NaN
  item19  item19    NaN       NaN NaN    NaN     NaN     NaN
  item20  item20    NaN       NaN NaN    NaN     NaN     NaN
  item21  item21    NaN       NaN NaN    NaN     NaN     NaN
  item22  item22    NaN       NaN NaN    NaN     NaN     NaN
  item23  item23    NaN       NaN NaN    NaN     NaN     NaN
  item24  item24    NaN       NaN NaN    NaN     NaN     NaN
  item25  item25    NaN       NaN NaN    NaN     NaN     NaN
  item26  item26    NaN       NaN NaN    NaN     NaN     NaN
  item27  item27    NaN       NaN NaN    NaN     NaN     NaN
  item28  item28    NaN       NaN NaN    NaN     NaN     NaN
  item29  item29    NaN       NaN NaN    NaN     NaN     NaN
  item30  item30    NaN       NaN NaN    NaN     NaN     NaN
  item31  item31    NaN       NaN NaN    NaN     NaN     NaN
  item32  item32    NaN       NaN NaN    NaN     NaN     NaN
  item33  item33    NaN       NaN NaN    NaN     NaN     NaN
  item34  item34    NaN       NaN NaN    NaN     NaN     NaN
  item35  item35    NaN       NaN NaN    NaN     NaN     NaN
  item36  item36    NaN       NaN NaN    NaN     NaN     NaN
  item37  item37    NaN       NaN NaN    NaN     NaN     NaN
  item38  item38    NaN       NaN NaN    NaN     NaN     NaN
  item39  item39    NaN       NaN NaN    NaN     NaN     NaN
  item40  item40    NaN       NaN NaN    NaN     NaN     NaN
  item41  item41    NaN       NaN NaN    NaN     NaN     NaN
  item42  item42    NaN       NaN NaN    NaN     NaN     NaN
  item43  item43    NaN       NaN NaN    NaN     NaN     NaN
  item44  item44    NaN       NaN NaN    NaN     NaN     NaN
  item45  item45    NaN       NaN NaN    NaN     NaN     NaN
  item46  item46    NaN       NaN NaN    NaN     NaN     NaN
  item47  item47    NaN       NaN NaN    NaN     NaN     NaN
  item48  item48    NaN       NaN NaN    NaN     NaN     NaN
  item49  item49    NaN       NaN NaN    NaN     NaN     NaN
  item50  item50    NaN       NaN NaN    NaN     NaN     NaN
  item51  item51    NaN       NaN NaN    NaN     NaN     NaN
  item52  item52    NaN       NaN NaN    NaN     NaN     NaN
  item53  item53    NaN       NaN NaN    NaN     NaN     NaN
  item54  item54    NaN       NaN NaN    NaN     NaN     NaN
  item55  item55    NaN       NaN NaN    NaN     NaN     NaN
  item56  item56    NaN       NaN NaN    NaN     NaN     NaN
  item57  item57    NaN       NaN NaN    NaN     NaN     NaN
  item58  item58    NaN       NaN NaN    NaN     NaN     NaN
  item59  item59    NaN       NaN NaN    NaN     NaN     NaN
  item60  item60    NaN       NaN NaN    NaN     NaN     NaN}]

# Seperate

In [18]:
def random_regression_with_kfold(df, cols, k=5, drawing=False):
    X = df[cols]
    y = df["label"]

    
    # Encode the target variable
    label_encoder = LabelEncoder()
    y_encoded = label_encoder.fit_transform(y)
    
    # Initialize the logistic regression model (multinomial for multiple categories)
    model = LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=200)
    
    # K-Fold Cross Validation
    kf = StratifiedKFold(n_splits=k, shuffle=True, random_state=42)
    accuracy_scores = []
    precision_scores = []
    recall_scores = []
    f1_scores = []
    # auc_scores = []
    # confusion_matrices = []
    # mean_p_values = []
    # std_p_values = []
    # mae_scores = []
    # mse_scores = []
    # r2_scores = []
    # rmse_scores = []
    # mean_coeffs = []
    # std_coeffs = []

    for train_index, test_index in kf.split(X, y_encoded):
        X_train, X_test = X.iloc[train_index], X.iloc[test_index]
        y_train, y_test = y_encoded[train_index], y_encoded[test_index]
        
        # Train the model
        model.fit(X_train, y_train)
        
        # Predict on the test set
        y_pred = model.predict(X_test)
        
        # Evaluate the model
        accuracy_scores.append(accuracy_score(y_test, y_pred))
        precision_scores.append(precision_score(y_test, y_pred, average='macro'))
        recall_scores.append(recall_score(y_test, y_pred, average='macro'))
        f1_scores.append(f1_score(y_test, y_pred, average='macro'))
        # mae_scores.append(mean_absolute_error(y_test, y_pred))
        # mse_scores.append(mean_squared_error(y_test, y_pred))
        # r2_scores.append(r2_score(y_test, y_pred))
        # rmse_scores.append(np.sqrt(mean_squared_error(y_test, y_pred)))
        
        # try:
        #     auc_scores.append(roc_auc_score(y_test, model.predict_proba(X_test), multi_class='ovr', average='macro'))
        # except ValueError:
        #     auc_scores.append(None)
        
        # confusion_matrices.append(confusion_matrix(y_test, y_pred))
        

    
    # Calculate mean and std scores across all folds
    mean_accuracy = np.mean(accuracy_scores)
    std_accuracy = np.std(accuracy_scores)
    mean_precision = np.mean(precision_scores)
    std_precision = np.std(precision_scores)
    mean_recall = np.mean(recall_scores)
    std_recall = np.std(recall_scores)
    mean_f1 = np.mean(f1_scores)
    std_f1 = np.std(f1_scores)
    # mean_auc = np.mean([score for score in auc_scores if score is not None])
    # std_auc = np.std([score for score in auc_scores if score is not None])
    # mean_p_value_mean = np.mean(mean_p_values)
    # std_p_value_mean = np.std(mean_p_values)
    # mean_p_value_std = np.mean(std_p_values)
    # std_p_value_std = np.std(std_p_values)
    # mean_mae = np.mean(mae_scores)
    # std_mae = np.std(mae_scores)
    # mean_mse = np.mean(mse_scores)
    # std_mse = np.std(mse_scores)
    # mean_r2 = np.mean(r2_scores)
    # std_r2 = np.std(r2_scores)
    # mean_rmse = np.mean(rmse_scores)
    # std_rmse = np.std(rmse_scores)

    
    if drawing:
        plt.figure(figsize=(8, 6))
        sns.heatmap(np.mean(confusion_matrices, axis=0), annot=True, fmt='.2f', cmap='Blues', xticklabels=label_encoder.classes_, yticklabels=label_encoder.classes_)
        plt.xlabel('Predicted')
        plt.ylabel('Actual')
        plt.title('Confusion Matrix')
        plt.show()
    
    return {
        "Mean Accuracy": mean_accuracy,
        "Std Accuracy": std_accuracy,
        "Mean Precision": mean_precision,
        "Std Precision": std_precision,
        "Mean Recall": mean_recall,
        "Std Recall": std_recall,
        "Mean F1 Score": mean_f1,
        "Std F1 Score": std_f1,
        # "Mean AUC": mean_auc,
        # "Std AUC": std_auc,
        # "Confusion Matrices": confusion_matrices,
        # "Mean P-Value (mean)": mean_p_value_mean,
        # "Std P-Value (mean)": std_p_value_mean,
        # "Mean P-Value (std)": mean_p_value_std,
        # "Std P-Value (std)": std_p_value_std,
        # "Mean Absolute Error (MAE)": mean_mae,
        # "Std Absolute Error (MAE)": std_mae,
        # "Mean Squared Error (MSE)": mean_mse,
        # "Std Squared Error (MSE)": std_mse,
        # "R-squared (R²) Score": mean_r2,
        # "Std R-squared (R²) Score": std_r2,
        # "Root Mean Squared Error (RMSE)": mean_rmse,
        # "Std Root Mean Squared Error (RMSE)": std_rmse,
        # "Mean Coefficient (mean)": mean_coeff_mean,
        # "Std Coefficient (mean)": std_coeff_mean,
        # "Mean Coefficient (std)": mean_coeff_std,
        # "Std Coefficient (std)": std_coeff_std,
    }



def get_n_rounds(files, items_count, rounds=1):
    """
    Becasue there are more human rows than LM, so we balance them by picking 300 human data 
    """
    all_results = []

    for _ in tqdm(range(rounds)):
        round_results = []
        for file in files:
            df = pd.read_excel(f'data/{file}')

            df_lm = df[df["label"] == "LM"].reset_index(drop=True)
            df_human = df[df["label"] == "Human"].reset_index(drop=True)
            df_human = df_human.sample(300).reset_index(drop=True)  # we only have 300 for LM
            
            df = pd.concat([df_lm, df_human], axis=0)
            cols_to_regres = [f"item{i}" for i in range(1, items_count+1)]  # Ensure your DataFrame has these columns
            
            res = random_regression_with_kfold(df, cols_to_regres, k=5, drawing=False)
            res["source"] = file
            round_results.append(res)
        all_results.append(pd.DataFrame(round_results))


    
    # Calculate average of each metric over all rounds
     # Concatenate all results and group by 'source' to calculate mean and std of numeric columns
    all_results_df = pd.concat(all_results)
    # print(all_results_df)
    numeric_cols = all_results_df.select_dtypes(include=np.number).columns
    averaged_results = all_results_df.groupby('source')[numeric_cols].mean().reset_index()

    return averaged_results, all_results_df

## BFI2

In [19]:
df_1, original_df_1 = get_n_rounds(files_bfi2, items_count=60, rounds=50)

100%|██████████| 50/50 [04:13<00:00,  5.07s/it]

In [20]:
df_1

,source,Mean Accuracy,Std Accuracy,Mean Precision,Std Precision,Mean Recall,Std Recall,Mean F1 Score,Std F1 Score
0,Human_GPT3.5_persona_BFI2.xlsx,0.918733,0.021776,0.921087,0.021280,0.918733,0.021776,0.918604,0.021845
1,Human_GPT3.5_shape_BFI2.xlsx,0.926967,0.016868,0.928515,0.016266,0.926967,0.016868,0.926891,0.016917
2,Human_GPT4_persona_BFI2.xlsx,0.953567,0.015080,0.955547,0.013691,0.953567,0.015080,0.953499,0.015146
3,Human_GPT4_shape_BFI2.xlsx,0.884933,0.022838,0.887895,0.021396,0.884933,0.022838,0.884671,0.023037
4,Human_LLaMA3_persona_BFI2.xlsx,0.957200,0.015859,0.958076,0.015581,0.957200,0.015859,0.957175,0.015875
5,Human_LLaMA3_shape_BFI2.xlsx,0.917739,0.019358,0.919119,0.019409,0.917791,0.019325,0.917673,0.019374

In [21]:
original_df_1

,Mean Accuracy,Std Accuracy,Mean Precision,Std Precision,Mean Recall,Std Recall,Mean F1 Score,Std F1 Score,source
0,0.910000,0.016997,0.911374,0.017105,0.910000,0.016997,0.909925,0.017012,Human_GPT3.5_persona_BFI2.xlsx
1,0.918333,0.009718,0.919711,0.009730,0.918333,0.009718,0.918266,0.009730,Human_GPT3.5_shape_BFI2.xlsx
2,0.958333,0.013944,0.960019,0.013048,0.958333,0.013944,0.958287,0.013978,Human_GPT4_persona_BFI2.xlsx
3,0.878333,0.026141,0.884467,0.018675,0.878333,0.026141,0.877660,0.027150,Human_GPT4_shape_BFI2.xlsx
4,0.943333,0.021985,0.944354,0.021691,0.943333,0.021985,0.943296,0.022006,Human_LLaMA3_persona_BFI2.xlsx
...,...,...,...,...,...,...,...,...,...
1,0.926667,0.016159,0.928022,0.015458,0.926667,0.016159,0.926600,0.016198,Human_GPT3.5_shape_BFI2.xlsx
2,0.951667,0.014337,0.953929,0.013178,0.951667,0.014337,0.951595,0.014385,Human_GPT4_persona_BFI2.xlsx
3,0.880000,0.014530,0.883300,0.013704,0.880000,0.014530,0.879728,0.014638,Human_GPT4_shape_BFI2.xlsx
4,0.966667,0.017480,0.967124,0.017221,0.966667,0.017480,0.966656,0.017488,Human_LLaMA3_persona_BFI2.xlsx
5,0.931275,0.014602,0.932316,0.014632,0.931412,0.014522,0.931247,0.014604,Human_LLaMA3_shape_BFI2.xlsx

## XEHAO

In [22]:
df_2, original_df_2 = get_n_rounds(files_hexao, 100, 50)

100%|██████████| 50/50 [14:45<00:00, 17.70s/it]

In [23]:
df_2

,source,Mean Accuracy,Std Accuracy,Mean Precision,Std Precision,Mean Recall,Std Recall,Mean F1 Score,Std F1 Score
0,Human_GPT3.5_persona_HEXAO.xlsx,0.979900,0.010895,0.980543,0.010509,0.979900,0.010895,0.979890,0.010904
1,Human_GPT3.5_shape_HEXAO.xlsx,0.980200,0.010512,0.980876,0.009995,0.980200,0.010512,0.980189,0.010524
2,Human_GPT4_persona_HEXAO.xlsx,0.964300,0.013288,0.965560,0.012738,0.964300,0.013288,0.964268,0.013312
3,Human_GPT4_shape_HEXAO.xlsx,0.948767,0.017452,0.951682,0.015830,0.948767,0.017452,0.948660,0.017535
4,Human_LLaMA3_persona_HEXAO.xlsx,0.993667,0.006484,0.993790,0.006351,0.993667,0.006484,0.993666,0.006485
5,Human_LLaMA3_shape_HEXAO.xlsx,0.969267,0.012513,0.970146,0.012054,0.969267,0.012513,0.969247,0.012529

In [24]:
original_df_2

,Mean Accuracy,Std Accuracy,Mean Precision,Std Precision,Mean Recall,Std Recall,Mean F1 Score,Std F1 Score,source
0,0.988333,0.008498,0.988734,0.008084,0.988333,0.008498,0.988329,0.008504,Human_GPT3.5_persona_HEXAO.xlsx
1,0.973333,0.006236,0.974226,0.005954,0.973333,0.006236,0.973320,0.006244,Human_GPT3.5_shape_HEXAO.xlsx
2,0.970000,0.006667,0.970628,0.006665,0.970000,0.006667,0.969990,0.006669,Human_GPT4_persona_HEXAO.xlsx
3,0.941667,0.013944,0.944357,0.012137,0.941667,0.013944,0.941561,0.014028,Human_GPT4_shape_HEXAO.xlsx
4,0.995000,0.006667,0.995135,0.006465,0.995000,0.006667,0.994999,0.006668,Human_LLaMA3_persona_HEXAO.xlsx
...,...,...,...,...,...,...,...,...,...
1,0.983333,0.009129,0.983599,0.008991,0.983333,0.009129,0.983330,0.009132,Human_GPT3.5_shape_HEXAO.xlsx
2,0.975000,0.011785,0.975603,0.011584,0.975000,0.011785,0.974991,0.011792,Human_GPT4_persona_HEXAO.xlsx
3,0.960000,0.024944,0.962627,0.021873,0.960000,0.024944,0.959894,0.025078,Human_GPT4_shape_HEXAO.xlsx
4,0.996667,0.006667,0.996774,0.006452,0.996667,0.006667,0.996666,0.006669,Human_LLaMA3_persona_HEXAO.xlsx
5,0.965000,0.016159,0.966414,0.015779,0.965000,0.016159,0.964969,0.016171,Human_LLaMA3_shape_HEXAO.xlsx

In [25]:
df_1 = df_1.round(3)
df_2 = df_2.round(3)

df_1.to_excel("result_bfi_raw.xlsx", index=False)

df_2.to_excel("result_xehao_raw.xlsx", index=False)